// Generated by CoffeeScript 1.6.1
(function() {

  this.DrawCtrl = function($scope) {
    $scope.entries = [
      {
        name: "John"
      }, {
        name: "Franklin"
      }, {
        name: "Betty"
      }
    ];
    $scope.addEntry = function() {
      $scope.entries.push($scope.newEntry);
      return $scope.newEntry = {};
    };
    $scope.countPairs = function() {
      var players;
      players = $scope.entries.length;
      if (players % 2 !== 0) {
        return players / 2 - 0.5;
      } else {
        return players / 2;
      }
    };
    return $scope.drawLucky = function() {
      return $scope.lucky = $scope.entries[Math.floor(Math.random() * $scope.entries.length)];
    };
  };

}).call(this);
