// Generated by CoffeeScript 1.6.1
(function() {

  this.DrawCtrl = function($scope) {
    $scope.entries = [
      {
        name: "John"
      }, {
        name: "Franklin"
      }, {
        name: "Betty"
      }
    ];
    return $scope.addEntry = function() {
      $scope.entries.push($scope.newEntry);
      return $scope.newEntry = {};
    };
  };

}).call(this);
